### ISSUE TITLE
Move roadmap into github wiki

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#63]
- [ ] Add blurb about flow control and link to a github issue
- [ ] Link to issues for known bugs (can be a Waffle query)
- [ ] Add link from README

**Comment by dmehra** [comment]
The wiki is here: https://github.com/juttle/juttle/wiki/Roadmap

Still need to add links from wiki items to github issues.
